Repository micronaut-projects/micronaut-reactor, pull requests merged in 2020-08, with the labels that each got.

#26 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#27 doc: remove example sections from README.md
  README.md
Labels: type: docs

#28 Add repository section
  src/main/docs/guide/repository.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#29 [reactor] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
