Repository micronaut-projects/micronaut-reactor, pull requests merged in 2023-05, with the labels that each got.

#284 Update to Micronaut Framework 4.0.0-M4
  gradle.properties
  gradle/libs.versions.toml
  reactor-http-client/build.gradle
  reactor-http-client/src/test/groovy/io/micronaut/reactor/http/client/TraceInterceptorSpec.groovy
  settings.gradle
Labels: type: dependency-upgrade

#249 Change all responses in ReactorHttpClient from Flux to Mono
  reactor-http-client/src/main/java/io/micronaut/reactor/http/client/BridgedReactorHttpClient.java
  reactor-http-client/src/main/java/io/micronaut/reactor/http/client/ReactorHttpClient.java
  reactor-http-client/src/test/groovy/io/micronaut/reactor/http/client/HttpGetSpec.groovy
  reactor-http-client/src/test/groovy/io/micronaut/reactor/http/client/JsonBodyBindingSpec.groovy
  reactor-http-client/src/test/groovy/io/micronaut/reactor/http/client/ReactorCrudSpec.groovy
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/toc.yml
Labels: status: next major version

#291 [reactor] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
